Project/Project/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tweeter.urls')),
    path('accounts/',include('accounts.urls'))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

Project/accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views
from accounts.views import UserDetailView,UserFollowView

app_name="accounts"


urlpatterns=[
path('',views.Registration,name="register"),
path('login/',auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
path('logout/',auth_views.LogoutView.as_view(template_name="accounts/logout.html"),name="logout"),
path('Profile/',views.ProfileView,name="profile"),
path('following/',views.followingView,name="following"),
path('followers/',views.followersView,name='followers'),
path('<username>/',UserDetailView.as_view(),name='userdetail'),
path('follow/<username>/',UserFollowView.as_view(),name="follow")
]

Project/tweeter/urls.py
from django.urls import path
from tweeter import views
app_name="tweeter"


urlpatterns=[
path('',views.Home,name="home"),
path('tweet/<id>/details/',views.TweetDetails,name="details"),
path('create/Post/',views.CreatTweetView,name="create"),
path('Post/Update/<id>/',views.UpdateView,name="update"),
path('delete/Post/<id>/',views.deleteView,name="delete"),
]

Project/accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager,AbstractBaseUser
from django.db.models.signals import post_save
from django.dispatch import receiver



class custommanager(BaseUserManager):
    def create_user(self,email,username,password=None,is_active=True,is_staff=False,is_admin=False):
        if not email:
            raise ValueError('User\'s must have an email.')
        if not password:
            raise ValueError('Users must have a password')
        if not username:
            raise ValueError('Users must have a username.')

        user_obj=self.model(
        email=self.normalize_email(email),
        username=username
        )
        user_obj.set_password(password)
        user_obj.is_active=is_active
        user_obj.is_admin=is_admin
        user_obj.is_staff=is_staff
        user_obj.save(using=self._db)

        return user_obj
    def create_staff(self,email,username,password=None):
        user=self.create_user(
        email,
        username,
        password=password,
        is_staff=True,
        )
        return user
    def create_superuser(self,email,username,password=None):
        user=self.create_user(
        email,
        username,
        password=password,
        is_staff=True,
        is_admin=True,
        )
        return user




class User(AbstractBaseUser):
    username=models.CharField(max_length=255,verbose_name="User Name",unique=True)
    timestamp=models.DateField(auto_now_add=True)
    first_name=models.CharField(max_length=256)
    last_name=models.CharField(max_length=255)
    email=models.EmailField(max_length=255,verbose_name="Email Address",unique=True)
    is_active=models.BooleanField(default=True)
    is_admin=models.BooleanField(default=False)
    is_staff=models.BooleanField(default=False)

    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['username']
    objects=custommanager()

    def __str__(self):
        return f'{self.username} {self.email}'

    def has_perm(self,perm,obj=None):
        return True
    def has_module_perms(self,app_label):
        return True

    @property
    def active(self):
        return self.active
    @property
    def staff(self):
        return self.staff
    @property
    def admin(self):
        return self.admin

class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    following=models.ManyToManyField(User,blank=True,related_name="followed_by")
    picture=models.ImageField(upload_to='Profile_picture',default="default.jpg")
    location=models.CharField(max_length=50,blank=True,null=True)
    bio=models.TextField(max_length=120)
    birth_date=models.DateField(blank=True,null=True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} {str(self.following.all().count())} following'
    class Meta:
        verbose_name_plural="UserProfile"
@receiver(post_save,sender=User)
def create_profile(sender,instance,created,**kwargs):
    if created:
        profile,new=UserProfile.objects.get_or_create(user=instance)

Project/tweeter/models.py
from django.db import models
from accounts.models import User
from tweeter.validators import validate_content

class Tweet(models.Model):
    content=models.TextField(max_length=500,validators=[validate_content])
    updated=models.DateTimeField(auto_now=True)
    timestamp=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="mypicts",blank=True,null=True)


    def __str__(self):
        return self.user.username

Project/accounts/forms.py
from django import forms
from django.forms import ModelForm
from accounts.models import User,UserProfile
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(ModelForm):
    password1=forms.CharField(label="Password",widget=forms.PasswordInput)
    password2=forms.CharField(label="Password Confirmation",widget=forms.PasswordInput)


    class Meta:
        model=User
        fields=('username','first_name','last_name','email')

    def clean_password2(self):
        password1=self.cleaned_data.get('password1')
        password2=self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Password don\'t match')
        return password2

    def save(self,commit=True):
        user=super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

class UserChangeForm(ModelForm):
    password=ReadOnlyPasswordHashField()
    class Meta:
        model=User
        fields=('username','first_name','last_name','password','is_admin','is_staff','is_active')
    def clean_password(self):
        return self.initial['password']
class RegistrationForm(ModelForm):
    password1=forms.CharField(label="Password",widget=forms.PasswordInput)
    password2=forms.CharField(label="Password Confirmation",widget=forms.PasswordInput)


    class Meta:
        model=User
        fields=('first_name','last_name','email','username')

    def clean_password2(self):
        password1=self.cleaned_data.get('password1')
        password2=self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Password don\'t match')
        return password2

    def save(self,commit=True):
        user=super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
class ProfilUpdateForm(ModelForm):
    class Meta:
        model=UserProfile
        fields=('bio','location','birth_date','picture')
class UserupdateForm(ModelForm):
    class Meta:
        model=User
        fields=('first_name','last_name','username')

Project/accounts/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from accounts.forms import RegistrationForm
from django.contrib import messages
from accounts.models import UserProfile,User
from accounts.forms import ProfilUpdateForm,UserupdateForm
from tweeter.models import Tweet
from django.views.generic import DetailView
from django.views import View



def Registration(request):
    if request.method=="POST":
        form=RegistrationForm(request.POST or None,request.FILES or None)
        if form.is_valid:
            form.save()
            messages.success(request,'Your account has successfully was successfully created')
            return HttpResponseRedirect('/accounts/login/')
    else:
        form=RegistrationForm()
    context={
    'formreg':form
    }
    return render(request,'accounts/registration.html',context)
def ProfileView(request):
    tweet=Tweet.objects.filter(user=request.user)
    prof=UserProfile.objects.get(user=request.user)
    userform=UserupdateForm(instance=request.user)
    profileform=ProfilUpdateForm(instance=prof)
    if request.method=='POST':
        userform=UserupdateForm(request.POST or None,request.FILES or None,instance=request.user)
        profileform=ProfilUpdateForm(request.POST or None,request.FILES or None,instance=prof)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            profileform.save()
            return HttpResponseRedirect('/')
    context={
    'prof':prof,
    'userform':userform,
    'profileform':profileform,
    'tweet':tweet
    }
    return render(request,'accounts/profile.html',context)
def followingView(request):
    followingObj=UserProfile.objects.filter(user=request.user)
    context={
    'followingObj':followingObj
    }
    return render(request,'accounts/following.html',context)
def followersView(request):
    followingObj=UserProfile.objects.filter(user=request.user)
    context={
    'followingObj':followingObj
    }
    return render(request,'accounts/followers.html',context)

class UserDetailView(DetailView):
    template_name = "accounts/userdetails.html"
    def get_object(self):
        return get_object_or_404(User,username__iexact=self.kwargs.get("username"))
class UserFollowView(View):
    def get(self,request,username,*args,**kwargs):
        toggle_user=get_object_or_404(User,username__iexact=username)
        if request.user.is_authenticated:
            user_profile,created=UserProfile.objects.get_or_create(user=request.user)
            if toggle_user in user_profile.following.all():
                user_profile.following.remove(toggle_user)
            else:
                user_profile.following.add(toggle_user)
                print(toggle_user)
        return HttpResponseRedirect(f'/accounts/{username}/')

Project/accounts/templates/accounts/followers.html
{%extends 'tweeter/base.html'%}
{%block content%}
<div class="card position-absolute col-sm-12 text-white" style=background-color:#131a2d;>
  <div class="card-header border-white sticky-top" style=background-color:#131a2d;>
    <div class="row">
      <div class="col-sm-6">
      <h4 class="text-white float-left"><a href="{%url 'tweeter:home'%}"><i class="fa fa-twitter fa-lg text-primary"></i></a><a style=margin-left:20px;>{{user.first_name}} {{user.last_name}}</a></h4>
      </div>
  </div>
  <a class="text-muted" style=margin-left:3rem;>@{{user.username}}</a>
  <div class="row" style=margin-top:7px;>
    <div class="col-sm-6">
      <a href="{%url 'accounts:followers'%}" class="nav-link active"><button class="btn border-primary shadow-lg col-sm-12" style=color:dodgerblue;>Followers</button></a>
      </div>
<div class="col-sm-6">
  <a href="{%url 'accounts:following'%}"><button class="btn text-muted border-muted col-sm-12">Following</button></a>
  </div>
    </div>
    </div>
    {%for followingObj in followingObj%}
    {%for profile in followingObj.user.followed_by.all%}
    <div class="row m-1">
    <div class="col-sm-1">
      image
    </div>
    <div class="col-sm-11">
      <div class="row">
        <div class="col-sm-9">
          <b><a href="{%url 'accounts:userdetail' profile.user.username%}" class="text-white">{{profile.user.first_name}} {{profile.user.last_name}}</a></b>
          <p class="text-muted">@{{profile.user.username}}</p>
          {{profile.bio}}

          </div>
          <div class="col-sm-3" align=right>
            <button class="btn btn-primary col-sm-12" style=border-radius:30px;>follow</button>
            </div>
        </div>
      </div>
      </div>
    <hr class="bg-secondary">
    {%endfor%}
    {%endfor%}
    </div>

{%endblock%}

Project/accounts/templates/accounts/following.html
{%extends 'tweeter/base.html'%}
{%block content%}
<div class="card position-absolute col-sm-12 text-white" style=background-color:#131a2d;>
  <div class="card-header border-white sticky-top" style=background-color:#131a2d;>
    <div class="row">
      <div class="col-sm-6">
      <h4 class="text-white float-left"><a href="{%url 'tweeter:home'%}"><i class="fa fa-twitter fa-lg text-primary"></i></a><a style=margin-left:20px;>{{user.first_name}} {{user.last_name}}</a></h4><br>

      </div>
  </div>
  <a class="text-muted" style=margin-left:3rem;>@{{user.username}}</a>
  <div class="row" style=margin-top:7px;>
<div class="col-sm-6">
  <a href="{%url 'accounts:followers'%}"><button class="btn text-muted border-muted col-sm-12">Followers</button></a>
  </div>
  <div class="col-sm-6">
    <a href="{%url 'accounts:following'%}" class="nav-link active"><button class="btn border-primary shadow-lg col-sm-12 active" style=color:dodgerblue;>Following</button></a>
    </div>
    </div>
</div>
{%for followingObj in followingObj%}
{%for following in followingObj.following.all%}
<div class="row m-1">
<div class="col-sm-1">
  image
</div>
<div class="col-sm-11">
  <div class="row">
    <div class="col-sm-9">
      <b><a href="{%url 'accounts:userdetail' following.username%}" class="text-white">{{following.first_name}} {{following.last_name}}</a></b>
      <p class="text-muted">@{{following.username}}</p>
      {{followingObj.bio}}

      </div>
      <div class="col-sm-3" align=right>
        <button class="btn btn-primary col-sm-12" style=border-radius:30px;>unfollow</button>
        </div>
    </div>
  </div>
  </div>
<hr class="bg-secondary">
{%endfor%}
{%empty%}
<h4 class="text-danger">Not following any users.</h4>
{%endfor%}
</div>
{%endblock%}

Project/accounts/templates/accounts/login.html
{%extends 'tweeter/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="card position-fixed col-sm-6 text-white" style=background-color:#131a2d;height:47rem;>
  <div class="card-header border-white sticky-top" style=background-color:#131a2d;>
    <div class="row">
      <div class="col-sm-3">
    <h4 class="text-white float-left"><a href="{%url 'tweeter:home'%}"><i class="fa fa-twitter fa-lg text-primary"></i></a><a style=margin-left:50px;>Tweet</a></h4>
      </div>
  </div>
    </div>
    <div class="col-sm-12" style=margin-top:8rem; align=center>
    <a href="" class="btn btn-primary col-sm-6"  data-toggle="modal" data-target="#modalPoll-1">Sign In</a>
    </div>
<div class="modal fade right" id="modalPoll-1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true" data-backdrop="false">
  <div class="modal-dialog modal-full-height modal-right modal-notify modal-info" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <p class="heading lead text-dark">Create Account</p>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="white-text">×</span>
        </button>
      </div>
      <form method="POST" action="" enctype="multipart/form-data">
      <div class="modal-body text-dark">
        {%csrf_token%}
        {{form|crispy}}

      </div>

      <div class="modal-footer justify-content-center">
        <button class="btn btn-primary">Login</button>

      </div>
      </form>
    </div>
  </div>
</div>
</div>

{%endblock%}

Project/accounts/templates/accounts/profile.html
{%extends 'tweeter/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="card position-absolute col-sm-12 text-white" style=background-color:#131a2d;>
  <div class="card-header border-white sticky-top" style=background-color:#131a2d;>
    <div class="row">
      <div class="col-sm-6">
      <h4 class="text-white float-left"><a href="{%url 'tweeter:home'%}"><i class="fa fa-twitter fa-lg text-primary"></i></a><a style=margin-left:20px;>{{user.first_name}} {{user.last_name}}</a></h4>
      {%for tweet in tweet%}
      <a class="text-muted">{{tweet.content.count}}</a>
      {%endfor%}
      </div>
  </div>
    </div>
    <div class="row">
      <div class="col-sm-7">
    <img src="{{prof.picture.url}}" width="150" height="150" class="rounded-circle m-1" alt="profile"><br>
    <b style=margin-left:30px;>{{user.first_name}} {{user.last_name}}</b>
    <br>
    <a style=margin-left:30px; class="text-muted">@{{user.username}}</a>
    <br>
    <div class="col-sm-10" style=margin-left:15px;margin-top:3px;>
    <a >{{prof.bio}}</a>
    <div class="row" style=margin-top:7px;>
      <div class="col-sm-6">
        <a class="text-muted"><i class="fa fa-map-marker fa-lg"></i> {{prof.location}}</a>
        </div>
        <div class="col-sm-6 text-muted">
          <a class="text-muted"><i class="fa fa-calendar" aria-hidden="true"></i> {{user.timestamp}}</a>
          </div>
      </div>
    </div>
    <div class="row" style=margin-top:7px;margin-left:15px;>
      <div class="col-sm-5">
        <a href="{%url 'accounts:following'%}" class="text-white">{{prof.following.count}} <a href="{%url 'accounts:following'%}" class="text-muted">Following</a></a>
        </div>
        <div class="col-sm-7">
          <a href="{%url 'accounts:followers'%}" class="text-white">{{prof.user.followed_by.count}} <a href="{%url 'accounts:followers'%}" class="text-muted">Followers</a></a>
          </div>
      </div>

    </div>
    <div class="col-sm-5">
          <div class="col-sm-12" style=margin-top:8rem; align=center>
          <a href="" class="btn btn-primary col-sm-6" style=border-radius:30px;  data-toggle="modal" data-target="#modalPoll-1">Edit Profile</a>
          </div>
      <div class="modal fade right position-fixed" id="modalPoll-1" tabindex="-1" role="dialog"  aria-labelledby="exampleModalLabel"
        aria-hidden="true" data-backdrop="false">
        <div class="modal-dialog modal-full-height modal-right modal-notify modal-info" role="document">
          <div class="modal-content" style=background-color:#131a2d;height:47rem;>
            <div class="modal-header">
              <p class="heading lead text-white">Edit profile</p>

              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true" class="text-white">×</span>
              </button>
            </div>
            <form method="POST" action="" enctype="multipart/form-data">
            <div class="modal-body text-white">
              {%csrf_token%}
              {{userform|crispy}}
              {{profileform|crispy}}
            </div>
            <div class="modal-footer justify-content-center">
              <button class="btn btn-primary">Save</button>
            </div>
            </form>
          </div>
        </div>
      </div>
      </div>
    </div>
    <div class="row" style=margin-left:5px;margin-top:20px;>
      <div class="col-sm-3" align=center>
        <a>Tweets</a>
        </div>
      </div>
    <hr class="bg-white">
    {% for tweet in tweet%}
    <div class="row">
      <div class="col-sm-1">
        img
        </div>
        <div class="col-sm-10">
          <b>{{tweet.user.first_name|capfirst}} {{tweet.user.last_name|capfirst}}</b> <a class="text-muted"> @{{tweet.user.username}} .
          {%if tweet.updated %} {{tweet.updated|timesince}} ago{%elif tweet.timestamp%}{{tweet.timestamp|timesince}} ago{%endif%}</a>
          <p>{{tweet.content}}</p>
          {%if tweet.image%}
          <img src="{{tweet.image.url}}" class="img-responsive col-sm-12" style=border-radius:25px; height="350" alt="myimg">
          {%endif%}

    </div>
    <div class="col-sm-1">
      <div class="btn-group dropleft float-right">
      <i type="button" class="fa fa-angle-down fa-lg float-right text-muted" data-toggle="dropdown" style=margin-right:20px; aria-haspopup="true" aria-expanded="false">
      </i>
      <div class="dropdown-menu border-white shadow-lg" style=height:10rem;background-color:#131a2d;>
        <a class="dropdown-item text-danger" href="{%url 'tweeter:delete' tweet.id%}"><i class="fa fa-trash fa-lg"></i> Delete</a>
        <a class="dropdown-item text-primary" href="{%url 'tweeter:update' tweet.id%}"><i class="fa fa-edit"></i> Edit</a>
      </div>
      </div>
    </div>
    </div>
    <hr class="bg-white">
    {%empty%}
    <h5 class="text-white">No tweets yet.</h5>
    {%endfor%}
    </div>

{%endblock%}

Project/accounts/templates/accounts/registration.html
{%extends 'tweeter/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="card position-fixed col-sm-6 text-white" style=background-color:#131a2d;height:47rem;>
  <div class="card-header border-white sticky-top" style=background-color:#131a2d;>
    <div class="row">
      <div class="col-sm-3">
      <h4 class="text-white float-left"><a href="{%url 'tweeter:home'%}"><i class="fa fa-twitter fa-lg text-primary"></i></a><a style=margin-left:50px;>Tweet</a></h4>
      </div>
  </div>
    </div>
    <div class="col-sm-12" style=margin-top:8rem; align=center>
    <a href="" class="btn btn-primary col-sm-6"  data-toggle="modal" data-target="#modalPoll-1">Sign Up</a>
    </div>
<div class="modal fade right" id="modalPoll-1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true" data-backdrop="false">
  <div class="modal-dialog modal-full-height modal-right modal-notify modal-info" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <p class="heading lead text-dark">Create Account</p>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="white-text">×</span>
        </button>
      </div>
      <form method="POST" action="" enctype="multipart/form-data">
      <div class="modal-body text-dark">
        {%csrf_token%}
        {{formreg|crispy}}

      </div>

      <div class="modal-footer justify-content-center">
        <button class="btn btn-primary">Register
        </button>

      </div>
      </form>
    </div>
  </div>
</div>
</div>
{%endblock%}

Project/accounts/templates/accounts/userdetails.html
{%extends 'tweeter/base.html'%}
{%block content%}
<div class="card position-absolute col-sm-12 text-white" style=background-color:#131a2d;>
  <div class="card-header border-white sticky-top" style=background-color:#131a2d;>
    <div class="row">
      <div class="col-sm-6">
      <h4 class="text-white float-left"><a href="{%url 'tweeter:home'%}"><i class="fa fa-twitter fa-lg text-primary">
      </i></a><a style=margin-left:20px;>{{user.first_name}} {{user.last_name}}</a></h4>
      </div>
  </div>
    </div>




    <div class="row" style=margin-top:1rem;>
      <div class="col-sm-7">
    <img src="{{prof.picture.url}}" width="150" height="150" class="rounded-circle m-1" alt="profile"><br>
    <b style=margin-left:30px;>{{user.first_name}} {{user.last_name}}</b>
    <br>
    <a style=margin-left:30px; class="text-muted">@{{user.username}}</a>
    <br>
    <div class="col-sm-10" style=margin-left:15px;margin-top:3px;>
    <a >{{prof.bio}}</a>
    <div class="row" style=margin-top:7px;>
      <div class="col-sm-6">
        <a class="text-muted"><i class="fa fa-map-marker fa-lg"></i> {{prof.location}}</a>
        </div>
        <div class="col-sm-6 text-muted">
          <a class="text-muted"><i class="fa fa-calendar" aria-hidden="true"></i> {{user.timestamp}}</a>
          </div>
      </div>
    </div>
    <div class="row" style=margin-top:7px;margin-left:15px;>
      <div class="col-sm-5">
        <a href="{%url 'accounts:following'%}" class="text-white">{{prof.following.count}} <a href="{%url 'accounts:following'%}" class="text-muted">Following</a></a>
        </div>
        <div class="col-sm-7">
          <a href="{%url 'accounts:followers'%}" class="text-white">{{prof.user.followed_by.count}} <a href="{%url 'accounts:followers'%}" class="text-muted">Followers</a></a>
          </div>
      </div>

    </div>
    <div class="col-sm-1"></div>
    <div class="col-sm-4">
      <a href="{%url 'accounts:follow' user.username%}"><button class="btn btn-primary float-right col-sm-12" style=border-radius:30px;>Follow</button></a>
      </div>
    </div>
<div class="row" style=margin-left:3rem;margin-top:1rem;>
  <div class="col-sm-3">
    <a>Tweets</a>
    </div>
    <div class="col-sm-3">
      <a>Tweets&Replies</a>
      </div>
      <div class="col-sm-3">
        <a>Media</a>
        </div>
        <div class="col-sm-3">
          <a>Likes</a>
          </div>

  </div>
<hr class="bg-secondary">

    {%for tweet in object.tweet_set.all%}
        <div class="row">

          <div class="col-sm-1">
            image
            </div>
          <div class="col-sm-10">
        <b><a href="{%url 'accounts:userdetail' tweet.user.username%}" class="text-white">{{tweet.user.first_name|capfirst}} {{tweet.user.last_name|capfirst}}</a></b> <a class="text-muted"> @{{tweet.user.username}} .
        {%if tweet.updated %} {{tweet.updated|timesince}} ago{%elif tweet.timestamp%}{{tweet.timestamp|timesince}} ago{%endif%}</a>
        <p>{{tweet.content}}</p>
        {%if tweet.image%}
        <img src="{{tweet.image.url}}" class="img-responsive col-sm-12" style=border-radius:25px; height="350" alt="myimg">
        {%endif%}
        </div>
        <div class="col-sm-1">
        <div class="btn-group dropleft float-right">
        <i type="button" class="fa fa-angle-down fa-lg float-right text-muted" data-toggle="dropdown" style=margin-right:20px; aria-haspopup="true" aria-expanded="false">
        </i>
        <div class="dropdown-menu border-white shadow-lg" style=height:10rem;background-color:#131a2d;>
          <a class="dropdown-item text-danger" href=""><i class="fa fa-trash fa-lg"></i> Delete</a>
          <a class="dropdown-item text-primary" href=""><i class="fa fa-edit"></i> Edit</a>
        </div>
        </div>
          </div>

          </div>

          <hr class="bg-white">
          {%empty%}
          {%if request.GET.q%}
          <h5 class="text-danger">Results Not Found!</h5>
          {%else%}
          <h5 class="text-white">No tweets yet.</h5>
          {%endif%}
    {%endfor%}


</div>
{%endblock%}