Project/Project/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tweeter.urls')),
    path('accounts/',include('accounts.urls'))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

Project/accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views
from accounts.views import UserDetailView,UserFollowView

app_name="accounts"


urlpatterns=[
path('',views.Registration,name="register"),
path('login/',auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
path('logout/',auth_views.LogoutView.as_view(template_name="accounts/logout.html"),name="logout"),
path('Profile/',views.ProfileView,name="profile"),
path('following/',views.followingView,name="following"),
path('followers/',views.followersView,name='followers'),
path('<username>/',UserDetailView.as_view(),name='userdetail'),
path('follow/<username>/',UserFollowView.as_view(),name="follow")
]

Project/tweeter/urls.py
from django.urls import path
from tweeter import views
app_name="tweeter"


urlpatterns=[
path('',views.Home,name="home"),
path('tweet/<id>/details/',views.TweetDetails,name="details"),
path('create/Post/',views.CreatTweetView,name="create"),
path('Post/Update/<id>/',views.UpdateView,name="update"),
path('delete/Post/<id>/',views.deleteView,name="delete"),
]

Project/tweeter/models.py
from django.db import models
from accounts.models import User
from tweeter.validators import validate_content

class Tweet(models.Model):
    content=models.TextField(max_length=500,validators=[validate_content])
    updated=models.DateTimeField(auto_now=True)
    timestamp=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="mypicts",blank=True,null=True)


    def __str__(self):
        return self.user.username

Project/tweeter/forms.py
from django import forms
from django.forms import ModelForm
from tweeter.models import Tweet


class TweetCreationForm(ModelForm):
    class Meta:
        content=forms.CharField(label=" ",widget=forms.Textarea(
        attrs={'placeholder':"What's happening?","class":"form-control"}))
        model=Tweet
        fields=('content','image')

Project/tweeter/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from tweeter.models import Tweet
from tweeter.forms import TweetCreationForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator
from accounts.models import UserProfile,User

@login_required
def Home(request):
    #im_following=UserProfile.objects.filter(following=following.user)
    tweet=Tweet.objects.all().order_by('-timestamp','-updated')
    query=request.GET.get('q',None)
    if query is not None:
        tweet=tweet.filter(Q(content__icontains=query)|Q(user__username__icontains=query))
    if request.method=="POST":
        form=TweetCreationForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            create=form.save(commit=False)
            create.user=request.user
            create.save()
            form=TweetCreationForm()
            return HttpResponseRedirect('/')
    else:
        form=TweetCreationForm()
    context={
    'tweet':tweet,
    'form':form,

    }
    return render(request,'tweeter/home.html',context)
@login_required
def TweetDetails(request,id):
    tweetdetails=Tweet.objects.get(id=id)
    context={
    'tweetdetails':tweetdetails
    }
    return render(request,'tweeter/details.html',context)
@login_required
def CreatTweetView(request):

    context={
    }
    return render(request,'tweeter/create.html',context)
@login_required
def UpdateView(request,id):
    if request.user.is_authenticated:
        tweetobj=Tweet.objects.get(id=id,user=request.user)
        form=TweetCreationForm(instance=tweetobj)
        if request.method=="POST":
            form=TweetCreationForm(request.POST or None,request.FILES or None,instance=tweetobj)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/')
    context={
    'form':form
    }
    return render(request,'tweeter/update.html',context)
@login_required
def deleteView(request,id):
    if request.user.is_authenticated:
        deleteTweet=Tweet.objects.get(id=id,user=request.user)
        deleteTweet.delete()
    return HttpResponseRedirect('/')

Project/tweeter/templates/tweeter/base.html
{%load static%}
{%load icons%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'style.css' %}" />
    <title>Hello, world!</title>
  </head>
  <body style=background-color:#374778;>
    <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        <div class="wrapper d-flex bg-white">
            <div class="sidebar" style=width:350px;>
                <ul style=margin-left:30px;>
                    <li><a href="{%url 'tweeter:home'%}"><i class="fa fa-home fa-lg m-1"></i>Home</a></li>
                    <li class="notification2"><a href="#"><i class="fa fa-envelope fa-lg m-1"></i>Messages</a><span class="number2">5</span></li>

                    {%if user.is_authenticated%}
                    <li><a href="{%url 'accounts:profile'%}"><i class="fa fa-user fa-lg m-1"></i>Profile</a></li>
                    <li><a href="{%url 'accounts:logout'%}"><i class="fa fa-sign-out fa-lg m-1"></i>Logout</a></li>
                    {%else%}
                    <li><a href="{%url 'accounts:login'%}"><i class="fa fa-sign-in fa-lg m-1" aria-hidden="true"></i>Login</a></li>
                    <li><a href="{%url 'accounts:register'%}"><i class="fa fa-sign-in fa-lg m-1" aria-hidden="true"></i>Register</a></li>
                    {%endif%}
                </ul>
            </div>
        </div>

        </div>

      <div class="col-sm-6 p-1" style=background-color:#131a2d;>
    {%block content%}
    {%endblock%}
  </div>
  <div class="col-sm-3">
    <div class="wrapper">
        <div class="sidebar" style=width:360px;>

        </div>
    </div>
  </div>
  </div>
</div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

Project/tweeter/templates/tweeter/details.html
{%extends 'tweeter/base.html'%}
{%block content%}
<div class="card text-white" style=background-color:#131a2d;>
  <div class="card-header border-white sticky-top" style=background-color:#131a2d;>
      <h4 class="text-white float-left"><a href="{%url 'tweeter:home'%}"><i class="fa fa-twitter fa-lg text-primary"></i></a> <a style=margin-left:50px;>Tweet</a></h4>
    </div>
    <div class="card-body" style=margin-left:25px;margin-right:25px;>
      <h5>{{tweetdetails.user.username}}</h5>
      <p>{{tweetdetails.content}}</p>
      {%if tweetdetails.image%}
      <p><img src="{{tweetdetails.image.url}}" class="img-responsive col-sm-12" style=border-radius:25px; height="500" alt="myimg"></p>
      {%endif%}
    <a class="text-muted">{%if tweetdetails.updated %}Updated {{tweetdetails.updated}}{%elif tweetdetails.timestamp%}{{tweetdetails.timestamp}}{%endif%}</a>
    <hr class="bg-white">
    Retweets   Likes
    <hr class="bg-white">
      </div>

    </div>


{%endblock%}

Project/tweeter/templates/tweeter/home.html
{%extends 'tweeter/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
    <div class="card text-white border-secondary" style=background-color:#131a2d;>
      <div class="card-header border-white sticky-top" style=background-color:#131a2d;>
        <div class="row">
          <div class="col-sm-3">
          <h4 class="text-white float-left"><a href="{%url 'tweeter:home'%}"><i class="fa fa-twitter fa-lg text-primary"></i></a><a style=margin-left:20px;>Home</a></h4>
          </div>
          <div class="col-sm-6">
          <form method="GET" action="{%url 'tweeter:home'%}" class="form-inline float-right">
        <input name="q" class="form-control form-control-sm ml-1 w-50" type="text" placeholder="Search" value="{{request.GET.q}}" aria-label="Search">
        <button class="btn"><i class="fa fa-search btn text-white"></i></button>
      </form>
      </div>
      <div class="col-sm-3">

        </div>
      </div>
        </div>


        <div class="card-body">

      <form method="POST" action="" enctype="multipart/form-data">
      {%csrf_token%}
      <a>{{form.content|as_crispy_field}}</a>
      <div class="card-footer">
        <div class="row">
          <div class="col-sm-6">
        {{form.image|as_crispy_field}}
        </div>
        <div class="col-sm-6" align=right>
      <button class="btn text-white col-12 col-md-5 col-sm-4" align=right style=background-color:#52a7e8;border-radius:30px;>Tweet</button>
      </div>
      </div>
      </div>
        </form>
        </div>
        <hr style=border:solid;>
{%for tweet in tweet%}
    <div class="row">

      <div class="col-sm-1">
        image
        </div>
      <div class="col-sm-10">
    <b><a href="{%url 'accounts:userdetail' tweet.user.username%}" class="text-white">{{tweet.user.first_name|capfirst}} {{tweet.user.last_name|capfirst}}</a></b> <a class="text-muted"> @{{tweet.user.username}} .
    {%if tweet.updated %} {{tweet.updated|timesince}} ago{%elif tweet.timestamp%}{{tweet.timestamp|timesince}} ago{%endif%}</a>
    <p>{{tweet.content}}</p>
    {%if tweet.image%}
    <img src="{{tweet.image.url}}" class="img-responsive col-sm-12" style=border-radius:25px; height="350" alt="myimg">
    {%endif%}
    </div>
    <div class="col-sm-1">
    <div class="btn-group dropleft float-right">
    <i type="button" class="fa fa-angle-down fa-lg float-right text-muted" data-toggle="dropdown" style=margin-right:20px; aria-haspopup="true" aria-expanded="false">
    </i>
    <div class="dropdown-menu border-white shadow-lg" style=height:10rem;background-color:#131a2d;>
      <a class="dropdown-item text-danger" href="{%url 'tweeter:delete' tweet.id%}"><i class="fa fa-trash fa-lg"></i> Delete</a>
      <a class="dropdown-item text-primary" href="{%url 'tweeter:update' tweet.id%}"><i class="fa fa-edit"></i> Edit</a>
    </div>
    </div>
      </div>

      </div>

      <hr class="bg-white">
      {%empty%}
      {%if request.GET.q%}
      <h5 class="text-danger">Results Not Found!</h5>
      {%else%}
      <h5 class="text-white">No tweets yet.</h5>
      {%endif%}
{%endfor%}
</div>



{%endblock%}

Project/tweeter/templates/tweeter/search.html
{%extends 'tweeter/base.html'%}
{%block content%}


{%endblock%}

Project/tweeter/templates/tweeter/update.html
{%extends 'tweeter/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="card text-white" style=background-color:#131a2d;>
  <div class="card-header border-white sticky-top" style=background-color:#131a2d;>
    <div class="row">
      <div class="col-sm-3">
      <h4 class="text-white float-left"><a href="{%url 'tweeter:home'%}"><i class="fa fa-twitter fa-lg text-primary"></i></a><a style=margin-left:50px;>Tweet</a></h4>
      </div>
      <div class="col-sm-9">
  </div>
  </div>
    </div>
    <div class="card-body">
  <form method="POST" action="" enctype="multipart/form-data">
  {%csrf_token%}
  {{form.content|as_crispy_field}}
  <div class="card-footer">
    <div class="row">
      <div class="col-sm-6">
    {{form.image|as_crispy_field}}
    </div>
    <div class="col-sm-6" align=right>
  <button class="btn text-white col-12 col-md-5 col-sm-4" align=right style=background-color:#52a7e8;border-radius:30px;>Tweet</button>
  </div>
  </div>
  </div>
    </form>
    </div>
    </div>
{%endblock%}